### PR TITLE
Add option to remove comments count for chrome and firefox

### PR DESCRIPTION
**Pull request by bkanhu**
Add option to remove comments/reply count for both chrome and firefox.

### CODE REVIEW

**Comment by bkanhu** [comment]
Resolves #55 for chrome and firefox

**Review by thomaswang — CHANGES_REQUESTED** [review]
Thanks so much! Do you mind using double quotes so we can clearly see the changes being made?

**Comment by bkanhu** [comment]
Hey, What I remembered I didn't change the double quote with a single quote. and while I trying to find out why it's happed I think the editor messed up the code because of some wrong config with prettier extensions. 
I think I need to change the whole thing again.😶 So right now I'm closing the PR.

**Comment by bkanhu** [comment]
Made a new PR. check #59

**Pull request closed without merging**
