### PR TITLE
Fix showing latest tweets

### LINKED ISSUE #25: Navigation bar text
I only want to have the icons on the side of my screen, I don't want the text e.g "Notifcation, Messages"

### PR DESCRIPTION
**Pull request by jadachoa**
Closes #25, #62, and fixes #45 that was broken with a timeline option update. It looks like Twitter was [testing this timeline option change](https://twitter.com/TwitterSupport/status/1463622357122273282), but their [help center now mentions it](https://help.twitter.com/en/using-twitter/twitter-timeline). I believe it's rolled out to everyone by now.

Tested on Firefox 95.0.1 (64-bit) and Chromium Version 96.0.4664.110 (Official Build) snap (64-bit) for Ubuntu.

### CODE REVIEW

**Comment by thomaswang** [comment]
Hi @jadachoa! Thanks for the PR again :)

I just shipped a major version and wanted to give you chance to re-submit this with the new version. I've started to port it over in https://github.com/thomaswang/minimal-twitter/commit/a829786853b8960732b458500a8c27c4484eda88 and https://github.com/thomaswang/minimal-twitter/commit/c82f65b6b5312ea4975e20ed930f2fa1a2e79b49. It doesn't seem to run on my test (Google Chrome Version 97.0.4692.71 (Official Build) (arm64)). Let me know if you can take a look!

**Review by thomaswang — CHANGES_REQUESTED** [review]
Will be easier to re-open a new PR with the new version! To start where I left off in the port, here are the necessary snippets you'll need to uncomment:
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L390
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L604
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L637
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L696
- https://github.com/thomaswang/minimal-twitter/blob/main/customize-app/components/controls/Extras.js#L7
- https://github.com/thomaswang/minimal-twitter/blob/main/customize-app/components/controls/Extras.js#L156

**Comment by thomaswang** [comment]
To start where I left off in the port, here are the necessary snippets you'll need to uncomment:
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L390
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L604
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L637
- https://github.com/thomaswang/minimal-twitter/blob/main/extension/content/main.js#L696
- https://github.com/thomaswang/minimal-twitter/blob/main/customize-app/components/controls/Extras.js#L7
- https://github.com/thomaswang/minimal-twitter/blob/main/customize-app/components/controls/Extras.js#L156

**Comment by jadachoa** [comment]
Hi Thomas, thank you for starting the port! I merged your work into the PR branch and committed my updated code for "Showing Latest Tweets".

I uncommented the lines in the `customize-app` directory and built it, and then moved the files that were output into the `extenstion` directory. I *think* I did it correctly, but please let me know if I made any mistakes. Awesome work on 4.0 by the way!

**Comment by thomaswang** [comment]
@jadachoa Oh awesome! Thanks, no need to move the output files, the `yarn build` commands takes care of that. I'll test this in a bit!

**Review by thomaswang — APPROVED** [review]

**Pull request merged**
